specfile_path: szafir-host-proxy.spec
upstream_package_name: szafir-host-proxy
downstream_package_name: szafir-host-proxy
upstream_project_url: https://github.com/deno/szafir-flatpak

actions:
  get-current-version:
    - python3 scripts/query_releases.py --current-version
  changelog-entry:
    - python3 scripts/query_releases.py --current-changelog
  create-archive:
    - bash scripts/packit_create_archive.sh

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all-x86_64
